[project]
name = "odoo-addons-oca-management-system"
version = "18.0.20241012.0"
dependencies = [
    "odoo-addon-mgmtsystem==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
